version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  spark:
    build: .
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./models:/app/models
    depends_on:
      - kafka
    command: python /app/src/streaming/streaming_detector.py

  dashboard:
    build: ./dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./data/alerts:/app/data/alerts
